version: '3.8'

services:
  aspose.microservice.webdownloader:
    image: ${DOCKER_REGISTRY:-aspose}/aspose-microservice-webdownloader
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Services/microservice.webdownloaderapi/Dockerfile
    ports:
      - 5001:5001

  aspose.microservice.webhtmlparser:
    image: ${DOCKER_REGISTRY:-aspose}/aspose-microservice-webhtmlparser
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Services/microservice.webhtmlparserapi/Dockerfile

  aspose.microservice.webcounter:
    image: ${DOCKER_REGISTRY:-aspose}/aspose-microservice-webcounter
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Services/microservice.wordcounterapi/Dockerfile 

  aspose.microservice.gateway:
    image: ${DOCKER_REGISTRY:-aspose}/aspose-microservice-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    build:
      context: .
      dockerfile: src/Services/microservice.gateway/Dockerfile


  aspose.microservice.webdownloader-api-dapr:
    image: "daprio/daprd:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: "service:aspose.microservice.webdownloader"
    depends_on:
      - aspose.microservice.webdownloader
      - db
    command: ["./daprd",
    "-app-id", "webdownloader-service",
    "-app-port", "5001",
    "-dapr-grpc-port", "50010",
    "-dapr-http-port", "5010",
    "-components-path", "./components"]
    volumes:
      - "./components/:/components"

  aspose.microservice.webhtmlparser-api-dapr:
    image: "daprio/daprd:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: "service:aspose.microservice.webhtmlparser"
    depends_on:
      - aspose.microservice.webhtmlparser
      - db
    command: ["./daprd",
    "-app-id", "htmlparser-service",
    "-app-port", "5002",
    "-dapr-grpc-port", "50020",
    "-dapr-http-port", "5020",
    "-components-path", "./components"]
    volumes:
      - "./components/:/components"

  aspose.microservice.webcounter-api-dapr:
    image: "daprio/daprd:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: "service:aspose.microservice.webcounter"
    depends_on:
      - aspose.microservice.webcounter
      - db
    command: ["./daprd",
    "-app-id", "webcounter-service",
    "-app-port", "5003",
    "-dapr-grpc-port", "50030",
    "-dapr-http-port", "5030",
    "-components-path", "./components"]
    volumes:
      - "./components/:/components"

# Zipkin
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411

# RabbitMQ
  rabbitmq:
        container_name: rabbitmq
        image: masstransit/rabbitmq:latest
        ports:
            - 5672:5672
            - 15672:15672
        restart: always

# Redis
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  db:
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    tty: true
    restart: always
    mem_limit: 3G
    cpu_count: 2
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
       - "8081:8081"
       - "8900:8900"
       - "8901:8901"
       - "8979:8979"
       - "10250:10250"
       - "10251:10251"
       - "10252:10252"
       - "10253:10253"
       - "10254:10254"
       - "10255:10255"
       - "10256:10256"
       - "10350:10350"
    volumes:
       - vol_cosmos:/data/db
volumes: 
  redis_data:
    driver: local
  vol_cosmos: